### ISSUE TITLE
New version breaks custom json and old customization

### ISSUE THREAD

**Issue by wolffan** [KrauseFx/TSMessages#118]
The new version breaks as soon as I create my own custom json for Design.
It fails serializing the json file:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'data parameter is nil'
**\* First throw call stack:
(
    0   CoreFoundation                      0x03b3f5e4 __exceptionPreprocess + 180
    1   libobjc.A.dylib                     0x038c28b6 objc_exception_throw + 44
    2   CoreFoundation                      0x03b3f3bb +[NSException raise:format:] + 139
    3   Foundation                          0x036099e2 +[NSJSONSerialization JSONObjectWithData:options:error:] + 67

**Comment by mRs-** [comment]
I just got the Error on the newest version of my app. No custom design of my notifications. Seems a new problem in my app without changing something in TSMessages.
