### ISSUE TITLE
TSMessage over the navigation bar? 

### ISSUE THREAD

**Issue by freak4pc** [KrauseFx/TSMessages#138]
I'm on iOS7 and my TSMessage always shows beneath the NavigationBar, Is there any way to make it "cover" the navigation bar and status bar? 

I'm using the following code:

``` obj-c
[TSMessage showNotificationInViewController:self.navigationController
                                              title:@"Test test"
                                           subtitle:@"This is a tester"
                                              image:nil type:TSMessageNotificationTypeSuccess
                                           duration:1.0
                                           callback:nil
                                        buttonTitle:nil
                                     buttonCallback:nil
                                         atPosition:TSMessageNotificationPositionTop
                               canBeDismissedByUser:YES];
```

**Comment by sammarks** [comment]
For anyone interested in a quick way to get this working (hopefully regardless of if you're using a TabViewController or a NavigationViewController), here's my approach that seems to work pretty well so far (going off of what @KrauseFx mentioned earlier):

Create a subclass of the TSMessage class (I called mine APMessage) and override the `defaultViewController` method like so:

```objc
+ (UIViewController *)defaultViewController {
    UIViewController *controller = [[UIViewController alloc] init];
    controller.view = [UIApplication sharedApplication].keyWindow;
    return controller;
}
```

**Comment by LandonRover** [comment]
@sammarks, that will cause your application to crash if you try to show a notification while another notification is showing.

**Comment by sammarks** [comment]
@LandonRover well that's not going to work! Have you been able to find a solution that prevents the crash?

**Comment by LandonRover** [comment]
I've just been using the `TSMessageNotificationPosition.NavBarOverlay` parameter in the following function (swift, objc would be `TSMessageNotificationPositionNavBarOverlay`)

```swift
TSMessage.showNotificationInViewController(navigationController!, 
  title: "some title", 
  subtitle: "some subtitle", 
  image: nil, 
  type: .Message, 
  duration: 2.0, 
  callback: nil, 
  buttonTitle: nil, 
  buttonCallback: nil, 
  atPosition: .NavBarOverlay, 
  canBeDismissedByUser: true)
```
