### ISSUE TITLE
Crash on `fadeOutNotification`

### ISSUE THREAD

**Issue by xanderdunn** [KrauseFx/TSMessages#16]
I have seen a crash occur a number of times on the `removeObjectAtIndex` NSMutableArray method called in `fadeOutNotification`.  

It seems only to crash when there is more than one TSMessage queued to be shown on screen.  It may happen when I tap a notification to dismiss it while it is already fading out.

[Here](https://github.com/thoughtadvances/storage/blob/master/objc/TSMessage.crash) is an example crash log showing this.

**Comment by shubhamzenext** [comment]
I am having same issue. The crash is visible in new relic crash analytics, I am not able to replicate the issue. How can I solve this crash?
