### ISSUE TITLE
Resources not included to bundle

### ISSUE THREAD

**Issue by choomz** [KrauseFx/TSMessages#174]
Hi there,

First, thanks for this cool library.

I'm actually facing a strange bug with this lib & cocoapods. Actually the lib crash because the file `TSMessagesDefaultDesign.json`is not embedded with the app.

So it crash here https://github.com/toursprung/TSMessages/blob/master/TSMessages/Views/TSMessageView.m#L69
because the file is not found.

I checked the sh file and actually everything looks ok : 

```
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundError.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundError@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundErrorIcon.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundErrorIcon@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundMessage.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundMessage@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundSuccess.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundSuccess@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundSuccessIcon.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundSuccessIcon@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundWarning.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundWarning@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundWarningIcon.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationBackgroundWarningIcon@2x.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationButtonBackground.png"
install_resource "TSMessages/TSMessages/Resources/Images/NotificationButtonBackground@2x.png"
install_resource "TSMessages/TSMessages/Resources/TSMessagesDefaultDesign.json"
```

The lib is included with 

```
pod "TSMessages"
```

in the pod file.

I also tried 

```
pod "TSMessages", "~> 0.9"
```

which is the same, it gives me the `0.9.9` version.

Maybe you have some clue ?

Thanks a lot !

**Comment by alex-samnas** [comment]
Hello, 
Thank for providing such an amazing library.

I have been using this library for a lot projects and always has been working great.

But I am trying to implement it in a project now and I have the same issue as above: 
the lib crash because the file TSMessagesDefaultDesign.json is not embedded with the app.

The lib is included with:
pod "TSMessages"

Thanks. :)

**Comment by cyrus86** [comment]
a work-around would be to include the resources files via the bundle resources of your build target (Build Phases -> Copy Bundle Resources -> Add Other...) 
not sure why this isn't handled automatically, though

**Comment by Jeremy-JJ** [comment]
@cyrus86  
Thanks your answer, my mistake has been resolved by your comment.
