### ISSUE TITLE
call a block when the message is gone

### ISSUE THREAD

**Issue by Pierre46** [KrauseFx/TSMessages#21]
Is it possible to have a block that is call when the message is gone ? Cause there is CallBack which is call only when the user dismissed the message by tapping on it or swiping it to the top. Do you think that we can also have a method like [TSMessage hide...]; in order to hide that actual message ? Anyway, great job ! thank you

**Comment by jlorich** [comment]
PR https://github.com/KrauseFx/TSMessages/pull/212 adds the option to execute the callback function when the message is faded out due to timeout
