### ISSUE TITLE
Appearance not working?

### ISSUE THREAD

**Issue by cytryn** [KrauseFx/TSMessages#210]
I am using the latest version but appearance seems not to be working

I am importing:

#import <TSMessages/TSMessageView.h>

![screen shot 2015-03-04 at 10 30 18 pm](https://cloud.githubusercontent.com/assets/735750/6519519/e43bd644-c393-11e4-8ae6-a1af1b2ceeeb.png)

**Comment by dorinsimina** [comment]
Same issue here

**Comment by KrauseFx** [comment]
Are you referring to https://github.com/KrauseFx/TSMessages/pull/196? If so, there was no new CocoaPods release in the mean time. You have to use the latest version from `:head`

Let me know if it works.

**Comment by cytryn** [comment]
Nice, it works...

Succeeded in changing fonts.

Is there a way to make the background transparent?

**Comment by mawhtin** [comment]
Can we push this to cocoapods? :D
