### ISSUE TITLE
Message under navigation bar in UITableViewController

### ISSUE THREAD

**Issue by loki187** [KrauseFx/TSMessages#222]
Hi,

I have UITableViewController with navigation bar and I want show TSMessage under navigation bar. I used:
    [TSMessage showNotificationInViewController:self.navigationController title:title subtitle:subtitle image:nil type:TSMessageNotificationTypeError duration:3.0 callback:nil buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionNavBarOverlay canBeDismissedByUser:YES];

but TSMessage is not under navigation bar.

When I tried:
  [TSMessage showNotificationInViewController:self title:title subtitle:subtitle image:nil type:TSMessageNotificationTypeError duration:3.0 callback:nil buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionNavBarOverlay canBeDismissedByUser:YES];

TSMessage is not visible, when my tableview is scrolled down.

**Comment by loki187** [comment]
Resolved.

**Comment by Ponf** [comment]
@loki187 could you share your solution please?

**Comment by loki187** [comment]
For UITableViewController inside UINavigationController I used:
```[TSMessage showNotificationInViewController:self title:title subtitle:subtitle image:nil type:TSMessageNotificationTypeError duration:3.0 callback:nil buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionTop canBeDismissedByUser:YES];```
Message is showed under the Navigation Bar.

When I use UIViewController inside UINavigationController:
```[TSMessage showNotificationInViewController:self title:title subtitle:subtitle image:nil type:TSMessageNotificationTypeError duration:3.0 callback:nil buttonTitle:nil buttonCallback:nil atPosition:TSMessageNotificationPositionNavBarOverlay canBeDismissedByUser:YES];```
