### ISSUE TITLE
Linker Error - Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by richardshergold** [KrauseFx/TSMessages#229]
I've not used Pods before but would like to try TSMessages.  I have followed the instructions for install (and then copied the demo view controller from the example project into my project).  When I build I get a linker error:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TSMessage", referenced from:
      objc-class-ref in TSDemoViewController.o

I have Build Achitecture Only set to YES
and my build architectures are "Standard Architectures (armv7, arm64)"

What do I need to do to make this work ?

thanks

**Comment by richardshergold** [comment]
I have got that to work now.

**Comment by swanback** [comment]
richardshergold:  I would love to know how you got that working.  Same problem here only with arm7:

ld: symbol(s) not found for architecture armv7

Thanks!
