### ISSUE TITLE
CocoaPods Spec

### ISSUE THREAD

**Issue by PatrickNegrettoLaser** [KrauseFx/TSMessages#241]
Hi, the 0.9.13 version is not accessible from default cocoapods spec, you can fix it?

 The last version available on pod install is 0.9.12

**Comment by LaserPatrick** [comment]
UP!!!!

**Comment by KrauseFx** [comment]
> UP!!!!

What do you mean? 

You know you can always use the latest version from the master branch by specifying your dependency in your `Podfile`?

**Comment by heyalexchoi** [comment]
Are you talking about grabbing the head with
```pod 'TSMessages', :head```?

The latest actual version is 0.9.12

**Comment by davidebettio** [comment]
With 
```
pod 'TSMessages', '~> 0.9'
```
the version installed is the 0.9.12, not the 0.9.13

**Comment by johnnypayso** [comment]
+1
