### ISSUE TITLE
Is there any plan for new version that will fix warnings?

### ISSUE THREAD

**Issue by lolgear** [KrauseFx/TSMessages#297]
Also it would be nice to eliminate HexColors dependency.

**Comment by KrauseFx** [comment]
Sorry no new releases are planned, as the project isn't maintained any more

**Comment by lolgear** [comment]
@KrauseFx 
Thanks for information!
Could you insert Deprecated warning into markdown readme as first section?
Also, could you insert this into project Description ( top of the Github repository page )?

**Comment by KrauseFx** [comment]
It's literally the first line of the README

> Notice: TSMessages is no longer being maintained/updated. We recommend everyone migrate to RMessage.

**Comment by lolgear** [comment]
@KrauseFx I mean "Deprecated warning into markdown readme as first section".

Section Title is not too big.
Example of section titles:

```
# Deprecated #
# No Maintenance #
# No PRs #
# Readonly #
```

I didn't see it and I created issue.
